services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=production
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=leave_management

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: