services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=production
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=leave_management
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USE_TLS=true
      - SMTP_USERNAME=example@example.com
      - SMTP_PASSWORD=example
      - SEND_EMAIL=True

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: